name: Ubuntu Build and Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 6.6.1
        cached: 'false'
    - name: ubuntu install GL library
      run: sudo apt-get install -y libglew-dev libglfw3-dev

    - name: Create build directory
      run: mkdir build

    - name: Configure and build
      run: |
        cd build
        cmake ..
        make
        cmake --build . --target all --config Release

    - name: zip build dir
      run: |
        zip -r build-Ubuntu.zip build

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          build-Ubuntu.zip
