name: Windows

permissions:
    contents: write

on: 
    push:
        tags:
          - 'v*'

jobs:
  build:
    name: Build
    runs-on: windows-2019
    strategy:
      matrix:
        include:
          # 6.2.2
          - qt_ver: 6.2.2
            qt_arch: win64_msvc2019_64
            msvc_arch: x64
            qt_arch_install: msvc2019_64
    env:
      targetName: HelloActions-Qt.exe
    # 步骤
    steps:
      # 安装Qt
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          # Version of Qt to install
          version: ${{ matrix.qt_ver }}
          # Target platform for build
          # target: ${{ matrix.qt_target }}
          arch: ${{ matrix.qt_arch }}
          cached: 'false'
          aqtversion: '==2.0.5'          
      # 拉取代码
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      # msvc编译
      - name: msvc-build
        id: build
        shell: cmd
        run: |
          cmake -S . -B .\build-BigWork3-Desktop_Qt_6_6_1_MSVC2019_64bit-Release
          cmake --build .\build-BigWork3-Desktop_Qt_6_6_1_MSVC2019_64bit-Release --target BigWork3 --config Release

      - name: windeployqt
        shell: cmd
        run: |
          cd .\build-BigWork3-Desktop_Qt_6_6_1_MSVC2019_64bit-Release\release
          windeployqt.exe BigWork3.exe

      # 打包
      - name: zip
        id: zip
        run: |
          $name = "${{ matrix.qt_ver }}-${{ matrix.qt_arch }}"
          echo $name
          # Compress-Archive -Path .\build-BigWork3-Desktop_Qt_6_6_1_MSVC2019_64bit-Release\BigWork3.exe -DestinationPath "${{ matrix.qt_ver }}-${{ matrix.qt_arch }}.zip"
          tar -a -c -f "${{ matrix.qt_ver }}-${{ matrix.qt_arch }}.zip" .\build-BigWork3-Desktop_Qt_6_6_1_MSVC2019_64bit-Release\release\*
          echo "::set-output name=artifactName::$name"
      
      # tag 上传Release
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ steps.zip.outputs.artifactName }}.zip
